name: Flask App CD
on:
  push:
    branches:
      - master

  workflow_dispatch:
  
jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@v6.0.2
        with:
          args: "ansible" 
          
  run-playbook:

		needs: [ validate ]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
          
      - name: Install dependencies Including Ansible
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r Ansible/requirements.txt
