name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: cicd
      DOCKER_IMAGE_TAG: latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} -f Dockerfile .

    - name: Run Docker Container
      run: |
        docker rm -f cicd || true
        docker run -d --name cicd -p 5000:5000 ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}

    - name: Additional Actions on Success
      if: success()
      run: echo "Pipeline succeeded! Perform additional actions here if needed."

    - name: Additional Actions on Failure
      if: failure()
      run: echo "Pipeline failed! Notify or rollback actions can be added here."
